# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170404_0209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказе'},
        ),
        migrations.RenameField(
            model_name='productinorder',
            old_name='nbm',
            new_name='nmb',
        ),
    ]
